openapi: 3.0.0
info:
  title: MikeAuto
  description: A Mike Auto Server based on OpenAPI 3.0 specification.
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: local server. Docker and API port mapped at 8080
paths:
  /car:
    get:
      summary: Returns a list of cars.
      description: List of cars in Mike Auto
      responses:
        '200':    # status code
          description: A JSON array of cars, owner description and maintainence description.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CarListResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'              
    post:
      summary: Add a new car record.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarRequest'
      responses:
        '201':
          description: Car created successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
  /car/{id}:
    get:
      summary: Read a car detail (using Id)
      parameters:
        - name: id
          in: path
          description: ID of the car
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detail of the requested car
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                
    put:
      summary: Update car details
      parameters:
        - name: id
          in: path
          description: ID of the car to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarUpdateRequest'
      responses:
        '200':
          description: Car details updated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'        
    delete:
      summary: Delete a car entry
      parameters:
        - name: id
          in: path
          description: Id of the car to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Car entry deleted
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CarListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              attributes:
                type: object
                properties:
                  vin:
                    type: string
                  plate:
                    type: string
                  state:
                    type: string
                  make:
                    type: string
                  model:
                    type: string
                  year:
                    type: string
                  ownerName:
                    type: string
                  address:
                    type: string
                  drivingLicenseNumber:
                    type: string
                  Id:
                    type: string
                  problemDescription:
                    type: string
                  dayIn:
                    type: string
                    format: date
                  dayOut:
                    type: string
                    format: date
                  mechanicName:
                    type: string
                required:
                  - vin
                  - plate
                  - state
                  - make
                  - model
                  - year
                  - ownerName
                  - address
                  - drivingLicenseNumber
                  - Id
                  - problemDescription
                  - dayIn
                  - dayOut
                  - mechanicName
            required:
              - type
              - attributes
    CarResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            attributes:
              type: object
              properties:
                vin:
                  type: string
                plate:
                  type: string
                state:
                  type: string
                make:
                  type: string
                model:
                  type: string
                year:
                  type: string
                ownerName:
                  type: string
                address:
                  type: string
                drivingLicenseNumber:
                  type: string
                Id:
                  type: string
                problemDescription:
                  type: string
                dayIn:
                  type: string
                  format: date
                dayOut:
                  type: string
                  format: date
                mechanicName:
                  type: string
              required:
                - vin
                - plate
                - state
                - make
                - model
                - year
                - ownerName
                - address
                - drivingLicenseNumber
                - Id
                - problemDescription
                - dayIn
                - dayOut
                - mechanicName
    CarRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              enum: [car]
            attributes:
              $ref: '#/components/schemas/CarAttributes'
          required:
            - type
            - attributes
    CarUpdateRequest:
        type: object
        properties:
          data:
            type: object
            properties:
              type:
                type: string
                enum: [car]
              attributes:
                $ref: '#/components/schemas/CarAttributes'
            required:
              - type
              - attributes
    CarAttributes:
      type: object
      properties:
        vin:
          type: string
        plate:
          type: string
        state:
          type: string
        make:
          type: string
        model:
          type: string
        year:
          type: string
        ownerName:
          type: string
        Address:
          type: string
        drivingLicenseNumber:
          type: string
        problemDescription:
          type: string
        dayIn:
          type: string
          format: date
        dayOut:
          type: string
          format: date
        mechanicName:
          type: string
      required:
        - vin
        - plate
        - state
        - make
        - model
        - year
        - ownerName
        - Address
        - drivingLicenseNumber
        - problemDescription
        - dayIn
        - dayOut
        - mechanicName
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        status:
          type: integer
          format: int32
          description: HTTP status code for the error response.
          example: 500
        message:
          type: string
          description: A detailed error message.
        stack:
          type: string
          description: The stack trace of the error.